// Auto-generated gallery
const gallery = [
  "/gallery/Elizabeth_Kitchen_Makeover/Before 1.jpeg",
  "/gallery/Elizabeth_Kitchen_Makeover/Before 2.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/Before 3.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/Before 4.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/Before 5.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/Before 6.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/IMG_7205.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/IMG_7206.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/IMG_7207.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/IMG_7210.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/IMG_7211.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/IMG_7212.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/IMG_7217.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/IMG_7247.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/IMG_7248.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/IMG_7249.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/IMG_7251.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/IMG_7252.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/IMG_7253.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/IMG_7254.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/IMG_7255.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/IMG_7256.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/IMG_7259.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/IMG_7261.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/IMG_7263.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/IMG_7378.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/IMG_7379.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/IMG_7380.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/IMG_7381.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/IMG_7382.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/IMG_7383.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/IMG_7384.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/IMG_7385.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/IMG_7386.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/IMG_7387.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/IMG_7389.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/IMG_7390.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/IMG_7391.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/IMG_7450.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/IMG_7451.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/IMG_7452.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/IMG_7453.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/IMG_7455.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/IMG_7457.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/IMG_7459.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/IMG_7460.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/IMG_7461.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/IMG_7471.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/IMG_7472.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/IMG_7473.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/IMG_7474.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/IMG_7476.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/IMG_7478.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/IMG_7479.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/IMG_7480.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/IMG_7481.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/IMG_7482.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/IMG_7484.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/IMG_7657.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/IMG_7658.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/IMG_7913.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/IMG_7914.jpg",
  "/gallery/Elizabeth_Kitchen_Makeover/IMG_7915.jpg"
];
export default gallery;
